# BarrelAttack

COMMENT_PRESS_BUTTON=何か押して下さい
COMMENT_HAKUSHUDE=手拍子で発射だ！
COMMENT_PLAYER1_READY=プレイヤー１の番だ！準備ＯＫ～？
COMMENT_PLAYER2_READY=プレイヤー２の番だ！準備ＯＫ～？
COMMENT_PLAYER3_READY=プレイヤー３の番だ！準備ＯＫ～？
COMMENT_PLAYER4_READY=プレイヤー４の番だ！準備ＯＫ～？
COMMENT_EMPOWER=連打でパワーをためろ！
COMMENT_DO_ADJUST=たたいて方向を調整できるぞ
COMMENT_ORDER_CHANGED=得点の低い順にトライしてくださ～いネ！
COMMENT_BADGE=左右で選択　START/PAUSEで決定

EXPLAIN_1_CAP=タルタルアタックの操作
EXPLAIN_1_CON1=・左右をたたいてパワーと方向を決めよう
EXPLAIN_1_CON2=・パワーがたまったら手拍子で発射
EXPLAIN_1_CON3=・空中でも少しだけ方向を調整できるぞ
EXPLAIN_2_CAP=対戦時の特別ルール
EXPLAIN_2_CON1=・待っている人は相手の木を揺らして
EXPLAIN_2_CON2=　邪魔することが出来ます。
EXPLAIN_2_CON3=　傾けたい方向のボタンを連打しよう！
EXPLAIN_3_CAP=ひとりプレイのルール
EXPLAIN_3_CON1=・計３回発射します
EXPLAIN_3_CON2=・３発目は得点が倍になります
EXPLAIN_3_CON3=

QUESTION_SWING_0_0=ＯＫ～！ハリキっていきましょ～！
QUESTION_SWING_0_1=収穫スタ～ト！！
QUESTION_SWING_1_0=ん～？なんか木がゆれてな～い？
QUESTION_SWING_1_1=ま、気にしないでレッツ収穫～！
QUESTION_SWING_2_0=オゥ～！木がゆれてるね～！
QUESTION_SWING_2_1=当たりにくいけどガンバってゴ～！
QUESTION_SWING_3_0=ヘイヘイ！右にかたむいてるヨ～！
QUESTION_SWING_3_1=右に向けてトンじゃうか～い？
QUESTION_SWING_4_0=ヘ～イ！左にかたむいちゃってるぜ！
QUESTION_SWING_4_1=左向きにイッちゃってチョ～ダイ！
QUESTION_SWING_5_0=大きく右にゆれちゃってるヨ！
QUESTION_SWING_5_1=ガンバって右にイッちゃってヨ！！
QUESTION_SWING_6_0=ン～！大きく左にゆれてるネ～！
QUESTION_SWING_6_1=うまく当たればベリ～ク～ルネ！
QUESTION_SWING_7_0=けっこう左右にゆれてるね～！
QUESTION_SWING_7_1=うまく合わせて　レッツゴ～！
QUESTION_SWING_8_0=木がノリノリでゆれてるヨ～！
QUESTION_SWING_8_1=こっちも負けずにノリノリでゴ～！！
QUESTION_SWING_9_0=バナナちゃ～ん、ゆれすぎだヨ！
QUESTION_SWING_9_1=ヘイ！ブラザ～！一言言ってやれヨ！
QUESTION_SWING_10_0=ヒュ～！どんだけゆれてんだヨ！
QUESTION_SWING_10_1=こうなったら底力を見せちゃえヨ！！
QUESTION_1KAIME1=１回目は　￥１００いただくゼィ
QUESTION_2KAIME1=２回目は　￥２００いただくゼィ
QUESTION_3KAIME1=３回目は　￥３００いただくゼィ
QUESTION_4KAIME1=４回目は　￥４００いただくゼィ
QUESTION_5KAIME1=５回目は　￥５００いただくゼィ
QUESTION_1KAIME2=挑戦するか～い？
QUESTION_KAIME2=やめたら残りはパ～！　挑戦する～？
QUESTION_ANS_YES1=ＯＫ～！　んじゃ、
QUESTION_ANS_YES2=かくごをきめて　レッツゴ～！！
QUESTION_1ANS_NO1=ありゃりゃ、やめちゃうの？
QUESTION_1ANS_NO2=どきょうついたら、またカモ～ン！
QUESTION_1ANS_FEW_TIP1=ヘイ！ユ～、チップたんないぜぃ
QUESTION_1ANS_FEW_TIP2=オ～ノゥ～！　また来てシ～ユ～！
QUESTION_2PRE1=ヘイ、ブラザ～！
QUESTION_2PRE2=まだまだカラダ　だいじょうぶぃ？
QUESTION_3PRE1=れんぞくアタック　だいじょうぶぃ？
QUESTION_3PRE2=ミ～はせきにんとれないネ～！
QUESTION_4PRE1=あんまりつづけるとアタマクラクラ
QUESTION_4PRE2=しな～い？
QUESTION_5PRE1=ドンキーも大砲もドクターストップ！
QUESTION_5PRE2=ラスト１発ね～！ＯＫ～？
QUESTION_2ANS_FEW_TIP1=ヘイ！ユ～、チップたんないぜぃ
QUESTION_2ANS_FEW_TIP2=今回の収穫はここまでネ～！
FUNKEY_COMPLETE1_1=ＯＫ～！　今回の収穫は
FUNKEY_COMPLETE1_2=これでエンドね～。グ～レイト！
FUNKEY_COMPLETE2_1=つぎもパーフェクトねらいでゴ～！
FUNKEY_COMPLETE2_2=バイバ～イ、また来てシ～ユ～！
QUESTION_NO_MORE1_1=オ～、ドンキ～、からだボロボロね
QUESTION_NO_MORE1_2=これ以上　ムリはダメダ～メ！
QUESTION_NO_MORE2_1=ザンネンだけど、今回はここまで！
QUESTION_NO_MORE2_2=また実ったらレッツトラ～イ！！
QUESTION_FOLD_UP1_1=ＯＫ～！　今回の収穫は
QUESTION_FOLD_UP1_2=これでエンドにしまショ～！
QUESTION_FOLD_UP2_1=残りは土にかえっちゃいマスネ～。
QUESTION_FOLD_UP2_2=また実ったらレッツトラ～イ！！
QUESTION_ORDER_CHANGED1=得点の低い順にトライしてくださ～いネ！
QUESTION_ORDER_CHANGED2=
QUESTION_FINAL_TERN1=ラストはスコアが
QUESTION_FINAL_TERN2=倍になっちゃうぜぃ！
QUESTION_PLAYER1_READY1=プレイヤー１の番だ！準備ＯＫ～？
QUESTION_PLAYER1_READY2=
QUESTION_PLAYER2_READY1=プレイヤー２の番だ！準備ＯＫ～？
QUESTION_PLAYER2_READY2=
QUESTION_PLAYER3_READY1=プレイヤー３の番だ！準備ＯＫ～？
QUESTION_PLAYER3_READY2=
QUESTION_PLAYER4_READY1=プレイヤー４の番だ！準備ＯＫ～？
QUESTION_PLAYER4_READY2=
QUESTION_RETRY1=リトライするならチップいらないヨ！
QUESTION_RETRY2=もういっちょやるか～い？
QUESTION_ABORT1=おっと！やめちゃうか～い？
QUESTION_ABORT2=

SCORE_BOARD_TERN1=１発目
SCORE_BOARD_TERN2=２発目
SCORE_BOARD_TERN3=３発目
SCORE_BOARD_SUM=合　計

YES=は　い
NO=いいえ

OKANE=お金
OKANE_RUBY=　　かね
SCORE=スコア

SCORE_ORDER1=１位
SCORE_ORDER2=２位
SCORE_ORDER3=３位
