# Trial

#1
TITLE=ＣＯＭＢＯ
STATUS=%s　／%s　コンボ
CONDITION=%sコンボを達成せよ
CONDITION_2P=２人で%sコンボを達成せよ
COMMENT=\n%sコンボまで\nつなげるのじゃ
COMMENT_2P=２人合わせて\n%sコンボまで\nつなげるのじゃ
COMMENT2=\n一度でも途切れたら\n０からやり直しじゃ
COMMENT2_2P=どちらかが途切れたら\n０からやり直しじゃ
COMMENT3=\n曲が終わったら\nタイムアウトで失格じゃぞ？
COMMENT3_2P=曲が終わったら\nタイムアウトで\n失格じゃぞ？
SUCCESS=\n合格じゃ！\n%sコンボ達成したぞぃ
SUCCESS_2P=合格じゃ！\n%sコンボ達成したぞぃ
FAIL=失格じゃ！\nコンボはチップ集めに\n一番重要じゃぞ？
FAIL_2P=失格じゃ！\nコンボはチップ集めに\n一番重要じゃぞ？
CAUTION=

#2
TITLE=手拍子
STATUS=手拍子　%s　／%s　回
CONDITION=手拍子を%s回たたけ
CONDITION_2P=２人で手拍子を%s回たたけ
COMMENT=\n手拍子を%s回たたくのじゃ
COMMENT_2P=２人合わせて手拍子を\n%s回たたくのじゃ
COMMENT2=\n連打もカウントするので\nがんばるのじゃぞ
COMMENT2_2P=連打もカウントするので\nがんばるのじゃぞ
COMMENT3=\nＢＡＤやＭＩＳＳは\n数に入らないのでな
COMMENT3_2P=ＢＡＤやＭＩＳＳは\n数に入らないのでな
SUCCESS=合格じゃ！\n手拍子%s回\nよくがんばった！
SUCCESS_2P=合格じゃ！\n手拍子%s回\nよくがんばった！
FAIL=失格じゃ！\nぜんぶ手拍子のつもりで\nやらんとのぅ
FAIL_2P=失格じゃ！\n手抜きをしたのは\nどっちじゃ？
CAUTION=

#3
TITLE=両面
STATUS=
CONDITION=両面を全てＧＲＥＡＴかＯＫでたたけ
CONDITION_2P=両面を全てＧＲＥＡＴかＯＫでたたけ
COMMENT=\n両面だけは確実にたたくのじゃ
COMMENT_2P=２人とも両面だけは\n確実にたたくのじゃ
COMMENT2=\nＢＡＤやＭＩＳＳは\n即、失格なのじゃ
COMMENT2_2P=ＢＡＤやＭＩＳＳは\n即、失格なのじゃ
COMMENT3=\nいつもより両面音符が\n多くなっとるようじゃぞ？
COMMENT3_2P=いつもより両面音符が\n多くなっとるようじゃぞ？
SUCCESS=合格じゃ！\n全ての両面を\nたたききったようじゃな
SUCCESS_2P=合格じゃ！\n全ての両面を\nたたききったようじゃな
FAIL=失格じゃ！\n両面同時に打つには\n集中力が足りんのぅ
FAIL_2P=失格じゃ！\n両面音符を甘くみては\nいかんぞ
CAUTION=

#4
TITLE=ドクロ
STATUS=%s　／%s　回
CONDITION=ドクロをたたかずに%s回たたけ
CONDITION_2P=ドクロをたたかずに%s回たたけ
COMMENT=\n音符に合わせて\nひたすらたたくのじゃ
COMMENT_2P=音符に合わせて\nひたすらたたくのじゃ
COMMENT2=\nドクロ音符は\n即、失格じゃぞ！
COMMENT2_2P=ドクロ音符は\n即、失格じゃぞ！
COMMENT3=\n慣れた曲なら、\nなおさら気をつけんといかん
COMMENT3_2P=となりにつられて\nドクロをたたかんように\n気をつけるのじゃ
SUCCESS=合格じゃ！\nドクロに一度も引っかからず、良くやった
SUCCESS_2P=合格じゃ！\n２人とも、うまくドクロを避けたようじゃな
FAIL=失格じゃ！ちょっと難しかったかのう？　じゃが、ドクロを\n必要以上に恐れてはイカンぞ！
FAIL_2P=今回は失格じゃが、\nドクロを必要以上に\n恐れてはイカンぞ！
CAUTION=

#5
TITLE=ポイント
STATUS=%s点
CONDITION=%s万点をとれ
CONDITION_2P=２人合わせて%s万点をとれ
COMMENT=\n%s万点をとるのじゃ
COMMENT_2P=２人合わせて\n%s万点をとるのじゃ
COMMENT2=\nドクロをたたけば\n０点になってしまうぞ
COMMENT2_2P=どちらかでも\nドクロをたたけば\n０点になってしまうぞ
COMMENT3=コンボをつなぐと\n高得点になるのは\n知っておるか？
COMMENT3_2P=たたきそこねると\n点数は減るのじゃぞ？
SUCCESS=\n合格じゃ！\n%s万点はやさし過ぎたかのぅ
SUCCESS_2P=合格じゃ！\n%s万点はやさし過ぎたかのぅ
FAIL=失格じゃ！\n普段から、点数を意識してないからこうなるのじゃ
FAIL_2P=失格じゃ！\n普段から点数も\n意識しておかんと・・・
CAUTION=

#6
TITLE=倍速
STATUS=
CONDITION=ノルマクリアせよ
CONDITION_2P=ノルマクリアせよ
COMMENT=いつもの\nストリートライヴのように\nノルマクリアするのじゃ
COMMENT_2P=いつもの\nストリートライヴのように\nノルマクリアするのじゃ
COMMENT2=\nいつもの倍のスピードで\n音符が流れるぞ
COMMENT2_2P=いつもの倍のスピードで\n音符が流れるぞ
COMMENT3=\n慣れた曲なら、\nカンタンじゃろうな
COMMENT3_2P=慣れた曲なら、\nカンタンじゃろうな
SUCCESS=合格じゃ！・・・まぁ、\nスピードは速いが\nタイミングは同じじゃからなぁ
SUCCESS_2P=合格じゃ！・・・まぁ、\nスピードは速いがタイミングは同じじゃからなぁ
FAIL=失格じゃ！\n流れは速いが\n曲のテンポは同じじゃぞ？
FAIL_2P=失格じゃ！流れは速いが\n曲のテンポは\n同じじゃぞ？
CAUTION=

#7
TITLE=ＰＯＷ
STATUS=
CONDITION=ＰＯＷタルをＧＲＥＡＴでたたけ
CONDITION_2P=ＰＯＷタルをＧＲＥＡＴでたたけ
COMMENT=\nＰＯＷタルを\nＧＲＥＡＴでたたくのじゃ
COMMENT_2P=ＰＯＷタルを\nＧＲＥＡＴでたたくのじゃ
COMMENT2=\nいつでてくるのか、\nわからんぞ
COMMENT2_2P=いつでてくるのか、\nわからんぞ
COMMENT3=\nじっくりと待つのじゃ
COMMENT3_2P=どちらかがはずしたら\n失格じゃからな
SUCCESS=\n・・・・一発合格じゃな
SUCCESS_2P=\n・・・・一発合格じゃな
FAIL=失格じゃ！\nたった１回\nたたくだけなのじゃが・・・
FAIL_2P=失格じゃ！\nたった１回\nたたくだけなのじゃが・・・
CAUTION=\nそろそろ来るようじゃぞ！

#8
TITLE=トランプ
STATUS=
CONDITION=トランプを３枚とも%sにせよ
CONDITION_2P=
COMMENT=ＳＴＯＰのついたタルが\n%sになるように\nたたくのじゃ
COMMENT_2P=
COMMENT2=ＧＲＥＡＴで、フォックス\nＯＫで、クリスタル\nＢＡＤで、スリッピーに\nなるのじゃからな
COMMENT2_2P=
COMMENT3=ＳＴＯＰは左、右、手拍子の\n３つの音符じゃ\nしかし、来る順番は\nわからんぞぃ
COMMENT3_2P=
SUCCESS=合格じゃ！\n３枚全て\n%sでそろったぞぃ
SUCCESS_2P=
FAIL=失格じゃ！\n３枚全て\n%sでそろっとらん
FAIL_2P=
CAUTION=

#9
TITLE=ファミコン
STATUS=
CONDITION=全てＧＲＥＡＴかＯＫでたたけ
CONDITION_2P=全てＧＲＥＡＴかＯＫでたたけ
COMMENT=ひとつでもたたきそこねると\nゲームオーバーじゃ\nゲームの曲はむずかしいのぅ
COMMENT_2P=ひとつでもたたきそこねるとゲームオーバーじゃ・・・ゲームの曲は\nむずかしいのぅ
COMMENT2=そう言えば、\nこのファミコン曲は\nもう持っておったかな？
COMMENT2_2P=そう言えば、\nこのファミコン曲は\nもう持っておったかな？
COMMENT3=\n順調じゃな
COMMENT3_2P=\n２人とも順調じゃな
SUCCESS=合格じゃ！\nさてはおぬし、\nファミコン得意じゃな？
SUCCESS_2P=合格じゃ！\nさてはおぬしたち、\nファミコン得意じゃな？
FAIL=・・・このテストに限っては、\n音楽センスより\nゲームセンスが必要かも\n知れん
FAIL_2P=・・このテストに限っては音楽センスより、ゲーム\nセンスが必要かも知れん
CAUTION=

#1０
TITLE=バトル
STATUS=
CONDITION=バトルでＣＯＭに勝て
CONDITION_2P=
COMMENT=
COMMENT_2P=
COMMENT2=
COMMENT2_2P=
COMMENT3=
COMMENT3_2P=
SUCCESS=
SUCCESS_2P=
FAIL=
FAIL_2P=
CAUTION=

#11
TITLE=反射神経
STATUS=
CONDITION=いきなり出てくる音符をたたけ
CONDITION_2P=いきなり出てくる音符をたたけ
COMMENT=\nＧＲＥＡＴかＯＫで\n３つたたくのじゃ
COMMENT_2P=ＧＲＥＡＴかＯＫで\n３つたたくのじゃ
COMMENT2=いつでてくるのか\nわからんから\n目がはなせないのじゃ
COMMENT2_2P=いつでてくるのか\nわからんから\n目がはなせないのじゃ
COMMENT3=じっくりと待つのじゃ\nドクロはたたいては\nいかんぞ
COMMENT3_2P=どちらかがはずしたり\nドクロをたたいたら、\n失格じゃからな
SUCCESS=\nなかなかの反射神経じゃな！
SUCCESS_2P=２人とも、なかなかの\n反射神経じゃな！
FAIL=失格じゃ！\n目をはなすなと\n言ったじゃろう？
FAIL_2P=失格じゃ！\n目をはなすなと\n言ったじゃろう？
CAUTION=\nＧＲＥＡＴかＯＫで\n３つ・・・・・

